### ISSUE TITLE
content assist does not work

### ISSUE THREAD

**Issue by b-smith-23** [IBM/vscode-clle#17]
No matter what I try I cannot get a list of parameters for the command

![image](https://github.com/IBM/vscode-clle/assets/150696892/b02e56ca-b349-4d8e-82ef-81604b21f79e)

**Comment by worksofliam** [comment]
When you connect, you get prompted to install CL tools. Did you do that?

**Comment by b-smith-23** [comment]
I didn't get prompted to install, but I already have the CLLE Language tools installed.
I only see a subset of CL commands

![image](https://github.com/IBM/vscode-clle/assets/150696892/4aba8c08-d9d0-44e4-8aa7-d708b1064cbc)
![image](https://github.com/IBM/vscode-clle/assets/150696892/2feaacb8-1005-4175-b02b-01922de554be)
![image](https://github.com/IBM/vscode-clle/assets/150696892/3c618501-64a9-4170-8236-efc8eac5db5c)

**Comment by worksofliam** [comment]
Can you try again but with Code for IBM i 2.6.1?

**Comment by b-smith-23** [comment]
Updated Code for IBM i to 2.6.1   CLLE language tools is 1.1.3

Still not working.

**Comment by worksofliam** [comment]
@b-smith-23 We did a fix to the language parser, can you try with the latest version?

**Comment by b-smith-23** [comment]
Seems to be working fine
