### ISSUE TITLE
Publish extension to Open VSX repository

### ISSUE THREAD

**Issue by chrjorgensen** [IBM/vscode-clle#6]
Could we have this extension published to the [Open VSX repository](https://open-vsx.org/) used by VSCodium and other VS Code clones?

For further info, see https://github.com/halcyon-tech/vscode-ibmi/issues/126

**Comment by worksofliam** [comment]
@chrjorgensen Yes, there is plans too. We're not allowed to use GitHub Actions to automate the release, so when we've got that part figured out we will publish onto OpenVSX too.

**Comment by chrjorgensen** [comment]
@worksofliam Friendly reminder... 😉

**Comment by chrjorgensen** [comment]
@worksofliam Friendly reminder... 😉

**Comment by SanjulaGanepola** [comment]
Published to Open VSX now -> https://open-vsx.org/extension/IBM/vscode-clle

Release process to Marketplace and Open VSX is automated so it will publish whenever releases are created in GitHub
